audit_header: false
title: Florida's Best Real Estate Training
description: Doug Leugers, a top Real Estate Agent in Florida, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Doug Leugers
  title:
  license_number:
  about_markdown: |
    Leugers Group, Powered By eXp Realty which represents the TOP 1% of Realtors in the United States as members of the National Association of Expert Advisors. Doug & Lona Leugers have been in the Real Estate business for a long time. They have over 23 years of combined experience, with specialties in the Luxury, Appraisal, Title, Auctioneer, and Commercial markets.
  market: Florida
  brand: Leugers Group
  brokerage: Brokered by eXp Realty
  address: 1625 SE 46th Street, Suite 4-A<br>Cape Coral FL 33904
  phone: 239-984-8838
  phone_type:
  phone2:
  phone2_type:
  email:
  url: http://searchfloridagulfhomes.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: "Join Our Team"
    CTA_text: "Let's talk about how The Leugers Group can take your business to new heights."
    CTA_link_text: "Contact"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/WeSellFlorida
  linkedin_url: http://www.linkedin.com/in/dougleugers
  gplus_url: https://plus.google.com/+DougLeugers
  youtube_url: https://www.youtube.com/user/dleugers
  twitter_url: https://twitter.com/_DLREA
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#171796'
  theme_color: '#212121'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
